apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: "cluster-autoscaler"
    app.kubernetes.io/name: "hetzner-cluster-autoscaler"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-9.9.2"
  name: cluster-autoscaler-cluster-autoscaler-additional
rules:
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - csidrivers
      - csistoragecapacities
    verbs:
      - list
      - get
