apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: "cluster-autoscaler"
    app.kubernetes.io/name: "hetzner-cluster-autoscaler"
    helm.sh/chart: "cluster-autoscaler-9.9.2"
  name: cluster-autoscaler-cluster-autoscaler-additional
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler-cluster-autoscaler-additional
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler-hetzner-cluster-autoscaler
    namespace: kube-system
